---

name:
    stack-templatizer
version:
    0.1.1.0
github:
    prikhi/stack-templatizer
homepage:
    https://github.com/prikhi/stack-templatizer#readme
license:
    BSD3
license-file:
    LICENSE
author:
    Pavan Rikhi
maintainer:
    pavan.rikhi@gmail.com
copyright:
    2020-2023 Pavan Rikhi
category:
    Development
extra-source-files:
    - README.md
    - CHANGELOG.md

synopsis:
    Generate a stack template from a folder.
description: |
    @stack-templatizer@ is an application that generates a @.hsfiles@ stack
    template from a folder of template files.

    You can install the application using @stack install
    stack-templatizer --resolver nightly@ or by cloning the repository and
    running @stack install@.

    Then run @stack-templatizer my-folder@ to turn all the files in @my-folder@
    into a @my-folder.hsfiles@ stack template.

    You can see an example folder & the generated @hs-files@ in the
    <https://github.com/prikhi/hpack-template hpack template repository>.

dependencies:
    - base >= 4.7 && < 5
    - bytestring < 1
    - directory >= 1 && < 2
    - filepath >= 1 && < 2

executables:
    stack-templatizer:
        source-dirs:
            src
        main:
            Main.hs
